### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by astannard** [conorhastings/react-code-window#4]
include a button in the header or footer of the window to copy the code to the users clipboard.

Great component BTW!!!

**Comment by conorhastings** [comment]
it unfortunately doesn't seem like there's a very good way to do this in javascript 😕 let me knwo if you have any ideas

**Comment by conorhastings** [comment]
@astannard i know it's been a pretty good while since this issue was created, but I just released `v2.0.0` supporting this!
